
DEFAULT_ROAD_CONFIG:
  driving_direction: right
  overtaking_rule: keep_right_pass_left
  lanes:
  - id: 1
    type: driving
    speed_limit_kmh: 130
  - id: 2
    type: driving
    speed_limit_kmh: 110
  - id: 3
    type: emergency
    speed_limit_kmh: 30